// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqj75B0WY57N-4y2xIo-lKcd7DKMr9e7M',
    appId: '1:789566449711:web:2d54e9bfee7b52a8d77eda',
    messagingSenderId: '789566449711',
    projectId: 'test-flutter-apps-35780',
    authDomain: 'test-flutter-apps-35780.firebaseapp.com',
    storageBucket: 'test-flutter-apps-35780.appspot.com',
    measurementId: 'G-YWS17YC85Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAToL1h5f_ACmSB7P-LqheSu36EOjkkjbU',
    appId: '1:789566449711:android:7d59fdd7e4619ef4d77eda',
    messagingSenderId: '789566449711',
    projectId: 'test-flutter-apps-35780',
    storageBucket: 'test-flutter-apps-35780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEiRIozaaDBopS7a3cqJmC_F8adYf1XTs',
    appId: '1:789566449711:ios:2729d44c548eb12dd77eda',
    messagingSenderId: '789566449711',
    projectId: 'test-flutter-apps-35780',
    storageBucket: 'test-flutter-apps-35780.appspot.com',
    iosBundleId: 'com.ajtortolero.authFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEiRIozaaDBopS7a3cqJmC_F8adYf1XTs',
    appId: '1:789566449711:ios:2729d44c548eb12dd77eda',
    messagingSenderId: '789566449711',
    projectId: 'test-flutter-apps-35780',
    storageBucket: 'test-flutter-apps-35780.appspot.com',
    iosBundleId: 'com.ajtortolero.authFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqj75B0WY57N-4y2xIo-lKcd7DKMr9e7M',
    appId: '1:789566449711:web:ca6f856427cace44d77eda',
    messagingSenderId: '789566449711',
    projectId: 'test-flutter-apps-35780',
    authDomain: 'test-flutter-apps-35780.firebaseapp.com',
    storageBucket: 'test-flutter-apps-35780.appspot.com',
    measurementId: 'G-Y7TMQFJ331',
  );
}
